[workspace]
members = ["crates/rlqt-lib", "crates/rlqt-cli", "crates/rlqt-ui"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["help", "color", "cargo", "env"] }
anyhow = "1.0"
thiserror = "2.0.16"
sysexits = "0.10"
tabled = { version = "0.20.0", features = ["ansi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-english = "0.1"
nom = "7.1"
log = "0.4"
fern = "0.7"
terminal_size = "0.4"
owo-colors = "4.1"
regex = "1.11"
bitflags = "2.6"
indicatif = "0.17"
num_enum = "0.7"
strum = { version = "0.26", features = ["derive"] }

sea-orm = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-sqlite", "macros"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
criterion = { version = "0.5", features = ["async_tokio"] }
rayon = "1.10"
proptest = "1.0"
