name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v\d\.\d+\.\d+'

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build_frontend:
    name: Build WASM and Frontend
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Rust compilation
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "frontend-wasm"
          cache-all-crates: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: crates/rlqt-ui/frontend/package-lock.json

      - name: Cache wasm-pack binary
        id: cache-wasm-pack
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/wasm-pack
          key: wasm-pack-0.14.0-${{ runner.os }}-${{ runner.arch }}

      - name: Install wasm-pack
        if: steps.cache-wasm-pack.outputs.cache-hit != 'true'
        run: cargo install wasm-pack --version 0.14.0

      - name: Build WASM module
        run: |
          wasm-pack build crates/rlqt-ql-wasm --target web --out-dir ../rlqt-ui/frontend/src/wasm/pkg

      - name: Build frontend
        run: |
          cd crates/rlqt-ui/frontend
          npm install
          npm run build

      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: crates/rlqt-ui/frontend/dist
          retention-days: 2

  release:
    name: Build and Archive
    needs: [build_frontend]

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # macOS, aarch64
          - target: aarch64-apple-darwin
            os: macos-latest
            target_rustflags: ''
          # Windows, x86-64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            target_rustflags: ''
          # Windows, aarch64
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
            target_rustflags: ''
          # Linux, x86-64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            target_rustflags: ''
          # Linux, aarch64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            target_rustflags: ''
          # Linux musl, x86-64 (static, for Alpine)
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            target_rustflags: ''
          # Linux musl, aarch64 (static, for Alpine)
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
            target_rustflags: ''

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Free up disk space
        if: startsWith(matrix.os, 'ubuntu')
        run: .github/scripts/free_disk_space.sh

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Download frontend dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: crates/rlqt-ui/frontend/dist

      - name: Install musl tools for static Linux builds
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl-dev

      - name: Install Nu Shell
        uses: hustcer/setup-nu@v3
        with:
          version: '0.100'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a rabbitmq-lqt release archive on macOS
        id: release-build-macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: nu ./scripts/release-macos.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
      - name: Store macOS build artifact
        id: upload-macos-artifact
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          retention-days: 2

      - name: Build a rabbitmq-lqt release archive on x86-64 Linux
        id: release-build-amd64-linux
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: nu ./scripts/release-linux.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
      - name: Store x86-64 Linux build artifact
        id: upload-amd64-linux-artifact
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          retention-days: 2

      - name: Build a rabbitmq-lqt release archive on aarch64 Linux
        id: release-build-aarch64-linux
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: nu ./scripts/release-linux.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
      - name: Store aarch64 Linux build artifact
        id: upload-aarch64-linux-artifact
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          retention-days: 2

      - name: Build a static rabbitmq-lqt release archive on x86-64 Linux (musl)
        id: release-build-amd64-linux-musl
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: nu ./scripts/release-linux.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
          CC_x86_64_unknown_linux_musl: clang
          CXX_x86_64_unknown_linux_musl: clang++
          AR_x86_64_unknown_linux_musl: ar
      - name: Store x86-64 Linux musl build artifact
        id: upload-amd64-linux-musl-artifact
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          retention-days: 2

      - name: Build a static rabbitmq-lqt release archive on aarch64 Linux (musl)
        id: release-build-aarch64-linux-musl
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
        run: nu ./scripts/release-linux.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
          CC_aarch64_unknown_linux_musl: clang
          CXX_aarch64_unknown_linux_musl: clang++
          AR_aarch64_unknown_linux_musl: ar
      - name: Store aarch64 Linux musl build artifact
        id: upload-aarch64-linux-musl-artifact
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}"
          retention-days: 2

      - name: Build a rabbitmq-lqt release archive on Windows x86-64
        id: release-build-windows
        if: ${{ matrix.target == 'x86_64-pc-windows-msvc' }}
        run: nu ./scripts/release-windows.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
      - name: Store Windows x86-64 build artifact
        id: upload-windows-artifact
        if: ${{ matrix.target == 'x86_64-pc-windows-msvc' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}.exe"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}.exe"
          retention-days: 2

      - name: Build a rabbitmq-lqt release archive on Windows aarch64
        id: release-build-windows-aarch64
        if: ${{ matrix.target == 'aarch64-pc-windows-msvc' }}
        run: nu ./scripts/release-windows.nu
        env:
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TARGET_RUSTFLAGS: ${{ matrix.target_rustflags }}
          SRC: ${{ github.workspace }}
          RLQT_SKIP_FRONTEND_BUILD: "1"
      - name: Store Windows aarch64 build artifact
        id: upload-windows-aarch64-artifact
        if: ${{ matrix.target == 'aarch64-pc-windows-msvc' }}
        uses: actions/upload-artifact@v4
        with:
          name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}.exe"
          path: "${{ github.workspace }}/target/${{ matrix.target }}/release/rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-${{ matrix.target }}.exe"
          retention-days: 2

  create_gh_release:
    needs: [release]
    runs-on: ubuntu-24.04
    steps:
    - name: Fetch macOS archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-aarch64-apple-darwin"
        path: ./artifacts
    - name: Fetch amd64 Linux archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-x86_64-unknown-linux-gnu"
        path: ./artifacts
    - name: Fetch aarch64 Linux archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-aarch64-unknown-linux-gnu"
        path: ./artifacts
    - name: Fetch x86-64 Linux musl (static) archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-x86_64-unknown-linux-musl"
        path: ./artifacts
    - name: Fetch aarch64 Linux musl (static) archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-aarch64-unknown-linux-musl"
        path: ./artifacts
    - name: Fetch Windows x86-64 archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-x86_64-pc-windows-msvc.exe"
        path: ./artifacts
    - name: Fetch Windows aarch64 archive
      uses: actions/download-artifact@v4
      with:
        name: "rabbitmq-lqt-${{ vars.NEXT_RELEASE_VERSION }}-aarch64-pc-windows-msvc.exe"
        path: ./artifacts
    - name: Publish rabbitmq-lqt release archive
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ vars.NEXT_RELEASE_VERSION }}
        draft: false
        files: ./artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
